# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emily Kate Koranda
email: ekoranda1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Emily Koranda's website. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emilykatekoranda.com" # the base hostname & protocol for your site
twitter_username: k_koranda
github_username:  ekoranda

# Build settings
markdown: kramdown
